import Head from "next/head";
import { Suspense, useRef, useState } from "react";
import { Canvas, useFrame, useThree } from "@react-three/fiber";
import { useGLTF, Environment } from "@react-three/drei";
import { EffectComposer, DepthOfField } from "@react-three/postprocessing";
import Header from "../components/canvas/dom/Header";
import Box from "../components/canvas/Box";
import Footer from "../components/canvas/dom/Footer";

export default function Home() {
  return (
    <div className="flex flex-col bg-black h-full">
      
      <Head>
        <title>R3F + Next + Tailwind Starter</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex-col h-screen">
        <div className="mx-auto items-center">
          <Header />
        </div>

        <div id='canvas-container' className='flex items-center'>
          <Canvas>
            <Box />
          </Canvas>
        </div>

      </main>
        <div className='m-10'>
          <Footer />
        </div>
    </div>
  );
}
